name: "Build Page"
on:
  push:

jobs:
  update_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build
        run: |
          pnpm run build --base=./

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: page-dist
          path: dist
